"""Shared pytest fixtures.

The regression suite drives TSSpy on the 4 yeast BAM validation set and
diffs each pipeline stage against canonical TSSr 0.99.6 ground-truth
artefacts. These artefacts live in the parent working tree (not inside
the package git repo) — see DATA_DIR below. Set TSSPY_TEST_DATA_DIR to
override.
"""
import os
import shutil
import subprocess
from pathlib import Path
import pytest

# Working tree containing BAMs + TSSr ground-truth files. Default is the
# TSSpy/TSSpy/.. parent which is the standard developer layout. CI / users
# without these big files should set TSSPY_TEST_DATA_DIR or skip the suite.
DATA_DIR = Path(
    os.environ.get("TSSPY_TEST_DATA_DIR",
                   Path(__file__).resolve().parents[2])
)

# Required inputs
REQUIRED_INPUTS = [
    "S01.sorted.bam", "S02.sorted.bam", "S03.sorted.bam", "S04.sorted.bam",
    "Scer.genome.fasta", "Scer.genome.fasta.fai",
    "saccharomyces_cerevisiae_R64-2-1.gff",
    # TSSr 0.99.6 ground-truth artefacts (generated by repro_tssr*.R)
    "tssr_repro_seqq10.TSS.tsv",
    "tssr_stage2_merged.TSS.tsv",
    "tssr_stage3a_normalized.TSS.tsv",
    "tssr_stage3b_poisson_normalized.TSS.tsv",
    "tssr_stage4_clusters_YPD.tsv",
    "tssr_stage4_clusters_Arrest.tsv",
    "tssr_stage5_consensus_YPD.tsv",
    "tssr_stage5_consensus_Arrest.tsv",
    "tssr_stage6_shape_PSS_YPD.tsv",
    "tssr_stage6_shape_PSS_Arrest.tsv",
    "tssr_stage6_shape_SI_YPD.tsv",
    "tssr_stage6_shape_SI_Arrest.tsv",
    "tssr_stage7_assigned_YPD.tsv",
    "tssr_stage7_assigned_Arrest.tsv",
    "tssr_stage7_unassigned_YPD.tsv",
    "tssr_stage7_unassigned_Arrest.tsv",
    "tssr_stage8_bw/YPD.TSS.processed.plus.bedGraph",
    "tssr_stage8_bw/YPD.TSS.processed.minus.bedGraph",
]


def _missing_inputs():
    return [p for p in REQUIRED_INPUTS if not (DATA_DIR / p).exists()]


@pytest.fixture(scope="session", autouse=True)
def _check_data_available():
    """Skip the whole suite if the validation data isn't present."""
    missing = _missing_inputs()
    if missing:
        pytest.skip(
            f"validation data missing in {DATA_DIR}; first 3: "
            f"{missing[:3]}. Set TSSPY_TEST_DATA_DIR or run repro_tssr*.R.",
            allow_module_level=True,
        )


@pytest.fixture(scope="session")
def data_dir():
    return DATA_DIR


@pytest.fixture(scope="session")
def workdir(tmp_path_factory):
    """One temp dir per session for all intermediate outputs."""
    return tmp_path_factory.mktemp("tsspy_regression")


def _tsspy_cli():
    """Return the tsspy entry point (prefers the installed script)."""
    if shutil.which("tsspy"):
        return ["tsspy"]
    return ["python", "-m", "TSSpy.main"]


def run_tsspy(*args, cwd=None):
    cmd = _tsspy_cli() + list(args)
    out = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    assert out.returncode == 0, (
        f"tsspy failed: cmd={cmd}\nstdout={out.stdout}\nstderr={out.stderr}")
    return out
